public class SetPractice {
    
    
    public static void runSetCode(){
        
        // declare Set of Integer and Assign to Set object 
        // Set is the collection of unique elements, it will only store unique values
        Set<Integer> nums = new Set<Integer>(); 
        nums.add(10); 
        nums.add(10); 
        nums.add(20); 
        nums.add(20); 
        nums.add(30); 
        nums.add(30); 
        
        System.debug('nums values are ' + nums);
        
    }
    

}